# Site settings
title: Writing School
email: "ben@hourigan.co"
description: > # this means to ignore newlines until "baseurl:"
  Writing School is a place to learn about writing. If you have a topic you'd like to see discussed, please write to ben@hourigan.co.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benhourigan.github.io/writingschool" # the base hostname & protocol for your site
twitter_username: writingschoolWS
# github_username:  benhourigan

# Build settings
markdown: kramdown

# Taken from https://github.com/barryclark/jekyll-now. Doesn't appear to work

footer-links:
  dribbble:
  email:
  facebook: https://www.facebook.com/writingschoolWS
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name> .

# Others

disqus:
  shortname: "writingschool"
